name: Test downstream projects

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyqt5 pytest
          pip install ipykernel[test]
          pip install --pre -U --upgrade-strategy=only-if-needed ipykernel
          pip install qtconsole[test]
          pip install --pre -U --upgrade-strategy=only-if-needed qtconsole
          pip install nbclient[test]
          pip install --pre -U --upgrade-strategy=only-if-needed nbclient
          pip install nbconvert[test]
          pip install --pre -U --upgrade-strategy=only-if-needed nbconvert
          pip install jupyter_server[test]
          pip install --pre -U --upgrade-strategy=only-if-needed jupyter_server
          pip install . --force-reinstall
          pip freeze
          python -c 'import jupyter_client; print("jupyter_client", jupyter_client.__version__)'

      - name: Test ipykernel
        if: ${{ always() }}
        run: pytest --pyargs ipykernel
      - name: Test nbclient
        if: ${{ always() }}
        run: IPYKERNEL_CELL_NAME="<IPY-INPUT>" pytest --pyargs nbclient
      - name: Test nbconvert
        if: ${{ always() }}
        run: pytest --pyargs nbconvert
      #qtconsole tests disabled because of a core dump
      #- name: Test qtconsole
      #  if: ${{ always() }}
      #  run: pytest --pyargs qtconsole
      #jupyter_server tests disabled because pip package doesn't allow for testing
      #see https://github.com/jupyter-server/jupyter_server/issues/563
      #- name: Test jupyter_server
      #  if: ${{ always() }}
      #  run: pytest --pyargs jupyter_server
